name: Check Code

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check code using Rustfmt
        run: cargo fmt --check
      
      - name: Check code using Clippy
        run: cargo clippy --release -- -D warnings --no-deps